FROM alpine:3.17

# Install GCC and Python
RUN apk update
RUN apk add g++
RUN apk add python3

# Set the working directory
WORKDIR /app

ARG LANG
ENV LANG="cpp"

# Copy the code file into the container
COPY ccode.txt .
COPY input.txt .
COPY output.txt .
COPY test_cases.py .

CMD ["python3", "test_cases.py"]