# Stage 1: Install Python
FROM alpine:latest as python-stage
WORKDIR /app
RUN apk add --no-cache python3
COPY test_cases.py .

# Stage 2: Build Java application
FROM openjdk:11-jdk-slim
WORKDIR /app
RUN apt-get update && apt-get install -y python3
COPY javacode.java .
RUN javac javacode.java

# Copy Python files from previous stage
COPY --from=python-stage /app/test_cases.py .

# Set the entry point to run the Python script
CMD ["python3", "test_cases.py"]