/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/T76mVuScEiX
 */
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"

export function ContestView() {
  return (
    <main className="flex items-center justify-center min-h-screen bg-gray-50 dark:bg-gray-900">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <a className="flex items-center justify-center" href="#">
          <CodeIcon className="h-6 w-6" />
          <span className="sr-only">Online Judge</span>
        </a>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <a className="text-sm font-medium hover:underline underline-offset-4" href="/contest-list">
            Contests
          </a>
          <a className="text-sm font-medium hover:underline underline-offset-4" href="/add-problem">
            Add Problem 
          </a>
          <a className="text-sm font-medium hover:underline underline-offset-4" href="/submissions">
            Submissions 
          </a>
          <a className="text-sm font-medium hover:underline underline-offset-4" href="/add-testcase">
            Add Test Cases 
          </a>
        </nav>
      </header>
      <div className="grid gap-4 w-full max-w-3xl p-4 rounded-lg border dark:border-gray-800">
        <div className="flex items-center gap-4">
          <h1 className="text-3xl font-bold tracking-tighter">Contest Problems</h1>
          <div className="ml-auto flex items-center gap-2">
            <div className="flex items-center gap-0.5">
              <ClockIcon className="w-4 h-4" />
              <span className="font-semibold">Time remaining:</span>
            </div>
            <div className="flex items-center gap-0.5">
              <span className="font-semibold">2h 30m 15s</span>
            </div>
          </div>
        </div>
        <div className="grid gap-4">
          <Card>
            <CardHeader className="flex items-center space-x-2">
              <CardTitle>Problem 1</CardTitle>
              <Badge variant="neutral">Unattempted</Badge>
            </CardHeader>
            <CardContent>
              <p className="text-sm leading-none">
                Description: You are given an array of integers. Your task is to find the sum of the elements of the
                array.
              </p>
            </CardContent>
            <CardFooter>
              <Button size="sm">View</Button>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader className="flex items-center space-x-2">
              <CardTitle>Problem 2</CardTitle>
              <Badge className="bg-green-200 text-green-800 dark:bg-green-500 dark:text-green-200" variant="positive">
                Accepted
              </Badge>
            </CardHeader>
            <CardContent>
              <p className="text-sm leading-none">
                Description: You are given an array of integers. Your task is to find the sum of the elements of the
                array.
              </p>
            </CardContent>
            <CardFooter>
              <Button size="sm">View</Button>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader className="flex items-center space-x-2">
              <CardTitle>Problem 3</CardTitle>
              <Badge className="bg-red-200 text-red-800 dark:bg-red-500 dark:text-red-200" variant="negative">
                Wrong Answer
              </Badge>
            </CardHeader>
            <CardContent>
              <p className="text-sm leading-none">
                Description: You are given an array of integers. Your task is to find the sum of the elements of the
                array.
              </p>
            </CardContent>
            <CardFooter>
              <Button size="sm">View</Button>
            </CardFooter>
          </Card>
        </div>
        <div className="flex flex-col gap-1 min-[400px]:flex-row justify-center">
          <a
            className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 border-gray-200 bg-white px-8 text-sm font-medium shadow-sm gap-1 transition-colors hover:bg-gray-100 hover:text-gray-900 dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-950 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300"
            href="#"
          >
            Submissions
          </a>
          <a
            className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow gap-1 transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
            href="#"
          >
            Leaderboard
          </a>
        </div>
      </div>
    </main>
  )
}


function ClockIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  )
}
