/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/AtlF4JYrzQO
 */
import { Button } from "@/components/ui/button"

export function LoginPage() {
  return (
    <div className="mx-auto max-w-sm space-y-8">
      <div className="space-y-2 text-center">
        <h1 className="text-3xl font-bold">Online Judge System</h1>
        <p className="text-gray-500 dark:text-gray-400">Sign in to continue</p>
      </div>
      <div className="space-y-4">
        <Button className="w-full">
          <div className="flex items-center justify-center space-x-2">
            <ChromeIcon className="w-5 h-5" />
            Sign in with Google
          </div>
        </Button>
      </div>
    </div>
  )
}


function ChromeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>
  )
}
